# Fancy indeks ve Pandas kütüphaneleri


In [1]:
import numpy  as np


In [2]:
x= np.array ([1,2,3,4])

In [3]:
x

array([1, 2, 3, 4])

In [4]:
print(x)

[1 2 3 4]


In [5]:
x.ndin

AttributeError: 'numpy.ndarray' object has no attribute 'ndin'

In [6]:
x.shape

(4,)

In [7]:
x>3

array([False, False, False,  True])

In [8]:
x[bi]

NameError: name 'bi' is not defined

In [9]:
x[bi]

NameError: name 'bi' is not defined

In [10]:
bi=x>3


In [11]:
bi

array([False, False, False,  True])

In [12]:
x[bi]

array([4])

In [13]:
#karesi sayının iki katına  eşit olan sayıları yazdınız



In [14]:
x

array([1, 2, 3, 4])

In [16]:
index=((x*2)==(x**2))

In [17]:
x*2

array([2, 4, 6, 8])

In [18]:
x**2

array([ 1,  4,  9, 16], dtype=int32)

In [19]:
print(x[index])

[2]
